### ISSUE TITLE
[Main issue thread] Long-press menu on comments

### ISSUE THREAD

**Issue by krestenlaust** [thunder-app/thunder#253]
**Is your feature request related to a problem? Please describe.**
Some of the features missing would make sense to introduce in a comment-context menu.

**Describe the solution you'd like**

- [x] #252 - Report comment
- [x] #232 - Share comment
- [x] #231 - Delete own comment
- [x] #251 - Copy comment text
- [x] #958 - Navigate to user profile

**Describe alternatives you've considered**
The actions should also be implemented as swipe gestures, that the user can customize but aren't active by default.

**Additional context**
#189 (Original issue)

**Comment by micahmo** [comment]
It looks like Report is the only outstanding action from this request. Would it make sense to create a new issue for just that one action?

**Comment by hjiangsu** [comment]
Adjusting the priority here because I think we should have the ability to report and delete comments (reporting in particular). For deleting comments, one way to do it would be to edit the comment instead to show nothing (not fully ideal, but it is a workaround)

**Comment by micahmo** [comment]
I thought delete was done in #415? And report is the only outstanding thing here?

**Comment by hjiangsu** [comment]
Oh shoot, I forgot about that one 😆 - yeah, in this case, just reporting comments/users would the the last outstanding issue!

**Comment by Toldry** [comment]
Please also add the option to go to the user's profile page from the comment context menu

**Comment by krestenlaust** [comment]
Awesome work!!
